field: 0c5a7e16-1f33-43bf-9206-34dc0d434109 # Recipe Contents
fieldLayouts:
  068fff99-ce76-4956-a7b3-bd4958c28ea2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 455872ed-5ffd-4ba9-9f94-b0d3b0cc7987 # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8121b2d0-e9af-4b27-a919-9762094b2c4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04f92383-9aff-40a5-b9d3-d5a8732f546e # Steps Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d86eb5ad-2f13-4877-b1f6-7777095ab830
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b8eb958-e4ad-409c-9ad4-7fc8a71a33de
        userCondition: null
fields:
  04f92383-9aff-40a5-b9d3-d5a8732f546e: # Steps Content
    columnSuffix: pvhzjzzw
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps Content'
    searchable: true
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults: null
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  455872ed-5ffd-4ba9-9f94-b0d3b0cc7987: # Steps Title
    columnSuffix: gumudrho
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
