fieldLayouts:
  3a5a899d-f4d8-4029-802a-234316e6fca3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4f67dddb-554c-46ff-a28c-05f89ba5a021
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06bf1aae-3991-4062-a25d-8b6acaeed58a # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a37b049-7acd-4509-aea6-be6c13715365
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e14a8476-ab04-4405-af3d-0cb3b1058277 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a73cfac7-9d6a-4c41-8fc2-893a32876cf1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a0fd6c7-f37b-4b13-acc0-d4eb85c2ba94 # Page Copy
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0971a439-d71d-416b-bb2a-bcc27a3e9068
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 474a8e34-c40e-4676-98bc-43403fb785f8 # About Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 420d5625-97c6-41c8-9104-2537d0e83b12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99e4cca4-b292-4750-a2cf-51002929e034
        userCondition: null
handle: aboutCraftyCoffee
hasTitleField: true
name: 'About Crafty Coffee'
section: 0b240244-3059-4fc7-b0d1-fc3ba35dae13 # About Crafty Coffee
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
