fieldLayouts:
  d4210e6d-82a8-40c1-9c18-f4735aec3e1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 044172fa-1f95-4e77-93e0-ec179d0a3d00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 053c8167-0f6b-4620-9d12-b9124a05906b
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: c62e8b1a-35c7-444b-b3bb-bffb6b25ce5b # Contact Us
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
