columnSuffix: null
contentColumnType: string
fieldGroup: 948f033a-b8d5-4c0b-a877-ff7e0633d5e5 # Styles
handle: drinkStyle
instructions: null
name: 'Drink Style'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add a drink style'
  showSiteMenu: false
  source: 'group:f7becdd1-23e8-47d5-b7bf-e8591338db92' # Drink Styles
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
