columnSuffix: dwhzsjcm
contentColumnType: text
fieldGroup: 008daf24-8a22-4578-a833-c59b744d40d2 # About
handle: subtitle
instructions: null
name: Subtitle
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
